package com.roudikk.composenavigator.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006a60)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF73f8e8)
val md_theme_light_onPrimaryContainer = Color(0xFF00201c)
val md_theme_light_secondary = Color(0xFF4a635f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcce8e3)
val md_theme_light_onSecondaryContainer = Color(0xFF051f1d)
val md_theme_light_tertiary = Color(0xFF46617a)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFcbe5ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001d32)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfafdfb)
val md_theme_light_onBackground = Color(0xFF191c1c)
val md_theme_light_surface = Color(0xFFfafdfb)
val md_theme_light_onSurface = Color(0xFF191c1c)
val md_theme_light_surfaceVariant = Color(0xFFdae5e2)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4947)
val md_theme_light_outline = Color(0xFF6f7977)
val md_theme_light_inverseOnSurface = Color(0xFFeff1ef)
val md_theme_light_inverseSurface = Color(0xFF2d3130)

val md_theme_dark_primary = Color(0xFF52dbcc)
val md_theme_dark_onPrimary = Color(0xFF003731)
val md_theme_dark_primaryContainer = Color(0xFF005048)
val md_theme_dark_onPrimaryContainer = Color(0xFF73f8e8)
val md_theme_dark_secondary = Color(0xFFb1ccc7)
val md_theme_dark_onSecondary = Color(0xFF1c3532)
val md_theme_dark_secondaryContainer = Color(0xFF324b47)
val md_theme_dark_onSecondaryContainer = Color(0xFFcce8e3)
val md_theme_dark_tertiary = Color(0xFFadc9e6)
val md_theme_dark_onTertiary = Color(0xFF16334a)
val md_theme_dark_tertiaryContainer = Color(0xFF2e4961)
val md_theme_dark_onTertiaryContainer = Color(0xFFcbe5ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1c)
val md_theme_dark_onBackground = Color(0xFFe0e3e1)
val md_theme_dark_surface = Color(0xFF191c1c)
val md_theme_dark_onSurface = Color(0xFFe0e3e1)
val md_theme_dark_surfaceVariant = Color(0xFF3f4947)
val md_theme_dark_onSurfaceVariant = Color(0xFFbec9c6)
val md_theme_dark_outline = Color(0xFF899391)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1c)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e1)

val seed = Color(0xFF29958a)
val error = Color(0xFFba1b1b)